function u = lane_keeping_controller(in1,rd)
%LANE_KEEPING_CONTROLLER
%    U = LANE_KEEPING_CONTROLLER(IN1,RD)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    02-Jun-2023 16:31:16

del = in1(5,:);
nu = in1(2,:);
psi = in1(3,:);
r = in1(4,:);
y = in1(1,:);
u = del.*(-3.218419449844997)-nu.*2.607074542078925e-2-psi.*2.236722592776642-r.*7.623015971412136e-2+rd.*7.623015971412136e-2-(sqrt(3.0e+1).*y)./6.0e+1;
