function u = longitudinal_regulator(in1,Vd)
%LONGITUDINAL_REGULATOR
%    U = LONGITUDINAL_REGULATOR(IN1,Vd)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    06-Jun-2023 16:45:10

Te = in1(2,:);
Vx = in1(1,:);
u = Te.*(-1.749597011297605)+sqrt(1.0e+1).*(Vd-Vx).*1.0e+1;
