function s = llm_phi_barrier_rules_text()
%LLM_PHI_BARRIER_RULES_TEXT  Shared phi barrier instructions (same as codes/phi_generation/run_llm_phi_ablation.m).
%   Aligns with phi_expr_passes_barrier_check: real/finite on [-2*emax, 2*emax], safe sqrt/log.

s = "Produce a unique safety barrier function expression in MATLAB syntax using variables 'e' (lateral error) and 'emax' (maximum allowed error; use the same numeric scale as your chosen e_max). " + ...
    "The function phi(e, emax) must satisfy: " + ...
    "1) phi(0, emax) >= 0 (usually 1) " + ...
    "2) phi(emax, emax) <= 0 " + ...
    "3) phi(-emax, emax) <= 0 " + ...
    "Here are some standard working examples: '1-(e/emax)^2', '1-(e/emax)^4', 'cos(pi*e/(2*emax))', or '1-abs(e/emax)'. " + ...
    "You may use the examples or return highly varied shapes that still satisfy the constraints (higher-order polynomials, fractional powers where defined, sech/tanh, bounded exponentials, squishing functions, etc.). ";

end
