function fx = lateral_fx(in1,mu)
%LATERAL_FX
%    FX = LATERAL_FX(IN1,MU)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    23-May-2023 16:53:06

Fxf = in1(5,:);
Psi = in1(8,:);
Vx = in1(1,:);
Vy = in1(2,:);
del = in1(4,:);
r = in1(3,:);
t2 = cos(Psi);
t3 = sin(Psi);
t4 = cos(del);
t5 = sin(del);
t8 = 1.0./Vx;
t9 = 1.0./mu;
t10 = r.*(5.0./2.0);
t11 = del.*5.0e+3;
t6 = Vx.*t4;
t7 = Vx.*t5;
t12 = -t10;
t13 = Vy+t10;
t14 = Vy+t12;
t15 = t4.*t13;
t16 = t5.*t13;
t17 = -t15;
t18 = t8.*t14;
t20 = t6+t16;
t19 = atan(t18);
t21 = t7+t17;
t22 = 1.0./t20;
t23 = t9.*t19.*(1.25e+2./2.94e+2);
t25 = t21.*t22;
t24 = tanh(t23);
t26 = atan(t25);
t27 = t26.*5.0e+3;
t28 = t11+t27;
t29 = (t9.*t28)./1.176e+4;
t30 = tanh(t29);
fx = [Vx.*(-1.0./1.2e+1)+(Fxf.*t4)./1.2e+3+Vy.*r-(1.0./t8.^2.*sign(Vx))./1.2e+1-mu.*t5.*t30.*(4.9e+1./5.0);(Fxf.*t5)./1.2e+3-Vx.*r-mu.*t24.*(4.9e+1./5.0)+mu.*t4.*t30.*(4.9e+1./5.0);(Fxf.*t5)./6.4e+2+mu.*t24.*2.94e+4+mu.*t4.*t30.*(1.47e+2./8.0);0.0;0.0;Vx.*t2-Vy.*t3;Vx.*t3+Vy.*t2;r];
