function [tireF,Fsat] = lateral_tireF(in1,mu)
%lateral_tireF
%    [tireF,Fsat] = lateral_tireF(IN1,MU)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    23-May-2023 16:53:06

Fxf = in1(5,:);
Vx = in1(1,:);
Vy = in1(2,:);
del = in1(4,:);
r = in1(3,:);
t2 = cos(del);
t3 = sin(del);
t6 = 1.0./Vx;
t7 = 1.0./mu;
t8 = r.*(5.0./2.0);
t9 = del.*5.0e+3;
t4 = Vx.*t2;
t5 = Vx.*t3;
t10 = -t8;
t11 = Vy+t8;
t12 = Vy+t10;
t13 = t2.*t11;
t14 = t3.*t11;
t15 = -t13;
t16 = t6.*t12;
t18 = t4+t14;
t17 = atan(t16);
t19 = t5+t15;
t20 = 1.0./t18;
t21 = t7.*t17.*(1.25e+2./2.94e+2);
t25 = t19.*t20;
t22 = tanh(t21);
t26 = atan(t25);
t23 = mu.*t22.*1.176e+4;
t27 = t26.*5.0e+3;
t24 = -t23;
t28 = t9+t27;
t29 = (t7.*t28)./1.176e+4;
t30 = tanh(t29);
t31 = mu.*t30.*1.176e+4;
tireF = reshape([Fxf,Fxf,0.0,0.0,t31,t31,t24,t24],[4,2]);
if nargout > 1
    Fsat = mu.*2.94e+3;
end
