function slipA = lugre_slipA(in1)
%lugre_slipA
%    slipA = lugre_slipA(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Jun-2023 12:36:49

Vx = in1(1,:);
Vy = in1(2,:);
del = in1(4,:);
r = in1(3,:);
t2 = 1.0./Vx;
slipA = [del-t2.*(Vy+r.*(2.1e+1./2.0e+1));-t2.*(Vy-r.*(1.61e+2./1.0e+2))];
