function slipR = lugre_slipR(in1)
%lugre_slipR
%    slipR = lugre_slipR(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Jun-2023 12:36:49

Ofl = in1(5,:);
Ofr = in1(6,:);
Orl = in1(7,:);
Orr = in1(8,:);
Vx = in1(1,:);
slipR = [(Ofl.*(1.3e+1./4.0e+1)-Vx)./max([Vx,Ofl.*(1.3e+1./4.0e+1)], [], 2, 'omitnan');(Ofr.*(1.3e+1./4.0e+1)-Vx)./max([Vx,Ofr.*(1.3e+1./4.0e+1)], [], 2, 'omitnan');(Orl.*(1.3e+1./4.0e+1)-Vx)./max([Vx,Orl.*(1.3e+1./4.0e+1)], [], 2, 'omitnan');(Orr.*(1.3e+1./4.0e+1)-Vx)./max([Vx,Orr.*(1.3e+1./4.0e+1)], [], 2, 'omitnan')];
