function gx = lugre_gx(in1,mu)
%LUGRE_GX
%    GX = LUGRE_GX(IN1,MU)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    08-Jun-2023 12:36:51

gx = reshape([0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0e+3],[9,2]);
