function gx = lateral_gx(in1,mu)
%LATERAL_GX
%    GX = LATERAL_GX(IN1,MU)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    23-May-2023 16:53:06

gx = reshape([0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0],[8,2]);
